### ISSUE TITLE
obecnie nie działa, błąd 406

### ISSUE THREAD

**Issue by karolzlot** [chawel/python-allegro#3]
@chawel , czy używasz nadal tej bioblioteki, działa Tobie? 

po zmianach które dodałem jako "Pull requests" udało mi się zalogować, ale nic nie mogę zrobić bo daje błąd 406

**Comment by chawel** [comment]
**26 WRZ 2018 - Zasoby do wystawiania i edycji ofert od dziś w wersji public**
[źródło: https://developer.allegro.pl/news/]

W nagłówkach: `accept` i `content-type` wywołania danego zasobu zmienić wartość:

`application/vnd.allegro.beta.v1+json` na `application/vnd.allegro.public.v1+json`
